import { Project } from "@/types";

export const projects: Project[] = [
  {
    slug: "customer-retention-analytics",
    name: "Customer Retention Analytics System",
    emoji: "",
    bgGradient: "linear-gradient(135deg, #F2ECE1, #E6F0EE, #B7DDDA)",
    tags: ["Python", "PostgreSQL", "Power BI", "Next.js"],
    category: "data-science",
    shortDesc:
      "An end-to-end customer retention analytics system for churn prediction, CLV estimation, revenue-at-risk analysis, and retention prioritization.",
    longDesc:
      "A full analytics pipeline that transforms raw customer churn data into business-ready insights, predictive churn scores, revenue-at-risk calculations, Power BI dashboards, and a custom React/Next.js EDA Insights Portal.",
    overview:
      "Customer churn is a major business problem because losing existing customers can reduce recurring revenue and increase acquisition costs. This project was built to answer a practical business question: which customers are most likely to leave, how much revenue is at risk, and what action should the retention team take first?\n\nThe system follows an end-to-end analytics workflow. Raw customer data is ingested into PostgreSQL, cleaned and validated using Python, transformed into a customer-level feature mart, and analyzed through exploratory data analysis. Multiple machine learning models are trained and compared, including Logistic Regression, Random Forest, and XGBoost. The selected model is then used to score customers by churn probability.\n\nThe final outputs include customer risk bands, estimated customer lifetime value, revenue-at-risk calculations, recommended retention actions, an interactive Power BI dashboard, and a custom React/Next.js EDA Insights Portal. The portal simulates BI-style interactions such as slicers, dynamic KPI cards, chart filtering, drill-down views, and sortable customer tables.",
    features: [
      "PostgreSQL data pipeline with raw, staging, and mart layers",
      "Python ETL scripts for ingestion, cleaning, validation, and feature engineering",
      "Customer feature mart generation for churn analysis and model training",
      "Exploratory data analysis for churn drivers, tenure groups, contract types, payment methods, and customer segments",
      "Machine learning model comparison using Logistic Regression, Random Forest, and XGBoost",
      "Weighted model score calculation using recall, ROC-AUC, F1-score, precision, and accuracy",
      "Customer-level churn probability scoring with Low, Medium, and High risk bands",
      "Estimated CLV and revenue-at-risk calculation for business prioritization",
      "Recommended retention actions based on customer risk and value",
      "Interactive Power BI dashboard with executive KPIs, churn drivers, customer segments, at-risk customers, and model performance pages",
      "Custom React/Next.js EDA Insights Portal with slicers, dynamic KPI cards, charts, drill-down views, and sortable customer tables",
    ],
    tech: [
      "Python",
      "pandas",
      "scikit-learn",
      "XGBoost",
      "PostgreSQL",
      "SQL",
      "Power BI",
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Recharts",
      "PapaParse",
    ],
    githubUrl: "https://github.com/Didera/ADD-YOUR-REPOSITORY-LINK",
    demoUrl: "https://add-your-demo-link.com",
    year: "2026",
    role: "Data Analyst, Machine Learning Developer & Frontend Developer",
  },

  {
    slug: "tracera",
    name: "TraceRa",
    emoji: "",
    bgGradient: "linear-gradient(135deg, #0d0f1a, #111a2e)",
    tags: ["Next.js", "NestJS", "PostgreSQL", "Socket.IO"],
    category: "data-science",
    shortDesc:
      "A full-stack traceability platform connecting Business Analysis, Project Management, development progress, and CI/CD visibility into one workflow.",
    longDesc:
      "TraceRa bridges the gap between business requirements and delivery — making every requirement traceable from business need to deployment.",
    overview:
      "What happens after a Business Analyst writes a requirement? That question became the starting point for TraceRa.\n\nTraceRa connects Business Analysis, Project Management, development progress, and CI/CD visibility into one traceable workflow. The main objective is to demonstrate how the Golden Workflow works in a real software delivery process: from creating a business requirement, approving it, converting it into development tasks, linking it with GitHub pull requests and CI/CD pipeline results, and finally tracking release readiness through a live dashboard.\n\nWhen requirements, acceptance criteria, approvals, and linked tasks are all visible in one place, team members can understand what needs to be built, why it matters, and what is considered complete — reducing confusion and keeping scope creep under control.",
    features: [
      "Requirement management with approval workflows and acceptance criteria",
      "Project and sprint tracking linked directly to requirements",
      "GitHub repository linking with pull request tracking",
      "CI/CD pipeline status updates via GitHub Webhooks and Actions",
      "Live dashboard and activity updates powered by Socket.IO",
      "Role-based access control (BA, PM, Developer, Stakeholder)",
      "Activity logs for full audit trail across the delivery lifecycle",
      "Release readiness tracking across all linked requirements and tasks",
    ],
    tech: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "NestJS",
      "PostgreSQL",
      "Prisma",
      "Docker",
      "Socket.IO",
      "JWT Auth",
      "GitHub Webhooks",
      "GitHub Actions",
    ],
    githubUrl:
      "https://github.com/Didera/Tracera---Project-Management-Platform",
    demoUrl: "https://tracera.example.com",
    year: "2025",
    role: "Full-Stack Developer & Data Pipeline Architect",
  },
  {
    slug: "neurolabs",
    name: "Neurolabs",
    emoji: "",
    bgGradient: "linear-gradient(135deg, #0a0f1a, #0f1a2e)",
    tags: ["Electron.js", "Python", "FastAPI", "Plotly"],
    category: "data-science",
    shortDesc:
      "An interactive desktop GUI for creating and training Machine Learning models without writing code — built for students and beginners.",
    longDesc:
      "Neurolabs makes experimenting with ML models accessible to beginners by removing the boilerplate, so users can focus on learning core concepts.",
    overview:
      "Neurolabs is an interactive GUI desktop application that lets users create, train, and evaluate Machine Learning models without writing code line by line.\n\nBuilt as a 2nd year group project, the application bridges a gap for students and beginners who want to experiment with ML workflows without getting blocked by implementation complexity. Users can upload datasets, configure models through an intuitive interface, and instantly visualize results — all without touching a single line of ML code.\n\nThe architecture splits cleanly into a desktop frontend built with Electron.js and a Python-powered ML engine exposed through a FastAPI middleware layer, allowing the two to communicate seamlessly.",
    features: [
      "Dataset upload and preview with feature selection",
      "Target variable configuration through a guided UI",
      "Support for multiple ML algorithms (classification, regression)",
      "One-click model training and evaluation",
      "Interactive visualizations — accuracy curves, confusion matrices, and more via Plotly",
      "Beginner-friendly interface designed to teach ML concepts through doing",
    ],
    tech: [
      "Electron.js",
      "Python",
      "FastAPI",
      "Plotly",
      "scikit-learn",
      "pandas",
      "NumPy",
    ],
    githubUrl: "https://github.com/Team-Voxel/neurolabs",
    demoUrl: "https://neurolabs.example.com",
    year: "2024",
    role: "Group Project — Data Science & ML",
  },

  {
    slug: "medicare-plus-digital-transformation",
    name: "MediCare Plus Digital Transformation",
    emoji: "",
    bgGradient: "linear-gradient(135deg, #0f1a1a, #0d2020)",
    tags: [
      "Business Analysis",
      "Agile Scrum",
      "BPMN 2.0",
      "Project Management",
    ],
    category: "business-analysis",
    shortDesc:
      "Comprehensive Business Analysis and Project Management plan for the digital transformation of a private healthcare provider across four outpatient clinics in Colombo.",
    longDesc:
      "Designed a full BA & PM plan transforming MediCare Plus from manual paper-based processes into a centralized digital ecosystem — covering patient mobile app, staff web portal, and EMR system.",
    overview:
      "MediCare Plus is a private healthcare provider operating four outpatient clinics in Colombo. The project focused on transforming existing manual, paper-based healthcare processes into a centralized digital ecosystem.\n\nThe proposed platform consists of a Patient Mobile Application, Clinic Staff Web Portal, and Electronic Medical Record (EMR) system supporting appointment management, online payments, digital medical records, prescriptions, referrals, notifications, and non-emergency nurse communication.\n\nA comprehensive requirements elicitation process was conducted using stakeholder interviews, focus groups, contextual observation, surveys, and document analysis. As-Is and To-Be business processes were modelled using BPMN 2.0, and the project was planned using Agile Scrum principles across an eight-month delivery timeline.",
    features: [
      "Requirements elicitation using stakeholder interviews, focus groups, contextual observation, surveys, and document analysis",
      "Comprehensive Gap Analysis between existing and proposed workflows",
      "As-Is and To-Be business process modelling using BPMN 2.0",
      "MVP scope definition including functional requirements, non-functional requirements, assumptions, and project boundaries",
      "Conceptual Entity Relationship Diagram (ERD) using Crow's Foot notation",
      "Epics, User Stories, and Acceptance Criteria for patient, doctor, receptionist, nurse, and administrator workflows",
      "Low-fidelity wireframes for key mobile and web application interfaces",
      "Work Breakdown Structure (WBS) with major deliverables and work packages",
      "Stakeholder analysis with Power–Interest Grid and engagement strategies",
      "Agile Product Backlog and Sprint Plan using Scrum principles",
      "Project team roles, responsibilities, resource requirements, and indicative cost estimate",
      "Role-Based Access Control, audit logging, and Sinhala/Tamil/English language support",
    ],
    tech: [
      "Business Analysis",
      "Requirements Engineering",
      "Project Management",
      "Agile Scrum",
      "BPMN 2.0",
      "Process Modelling",
      "Gap Analysis",
      "ER Modelling",
      "User Stories",
      "Acceptance Criteria",
      "Wireframing",
      "WBS",
      "Risk Management",
      "Stakeholder Management",
      "Product Backlog",
      "Sprint Planning",
    ],
    githubUrl:
      "https://drive.google.com/drive/folders/1hTlSlaKw-RIwULhXIuoV5aJIm1Zhf4aU?usp=sharing",
    demoUrl: "https://add-your-demo-link.com",
    year: "2025",
    role: "Business Analyst & Project Manager",
  },
];
export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
